#!/bin/bash
#
# Init file for searchd
#
# chkconfig: 2345 55 25
#
# description: searchd 
#
# USE "chkconfig --add searchd" to configure Sphinx searchd service
#
# by Steve Kamerman April 14, 2010
# http://www.tera-wurfl.com
# public domain
#
### BEGIN INIT INFO
# Provides:          {{user}}_searchd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
### END INIT INFO

SUDO_USER={{user}}

PID_FILE='/home/{{user}}/run/searchd.pid'
CONFIG_FILE=/home/{{user}}/etc/sphinxsearch/sphinx.conf
EXEC_PATH=/usr/local/bin
RETVAL=0
prog="searchd"

do_start() {
    echo "Starting $prog"
    sudo -u $SUDO_USER $EXEC_PATH/$prog --config $CONFIG_FILE
    RETVAL=$?
    echo
    return $RETVAL
}

do_stop() {
    echo "Stopping $prog"
    if [ -e $PID_FILE ] ; then
        sudo -u $SUDO_USER $EXEC_PATH/$prog --stop --config $CONFIG_FILE
        sleep 2
        if [ -e $PID_FILE ] ; then
            echo "WARNING: searchd may still be alive: $PID_FILE"
        fi
    fi
    RETVAL=$?
    echo
    return $RETVAL
}

do_status() {
    RETVAL=$?
    if [ -e $PID_FILE ] ; then
        sudo -u $SUDO_USER $EXEC_PATH/$prog --status --config $CONFIG_FILE
        echo "---"
        echo "$prog is running (`cat $PID_FILE`)"
    else
        echo "$prog is not running"
    fi
    return $RETVAL
}

do_reindex() {
    echo "Reindexing all $prog indices"
        if [ -e $PID_FILE ]  ; then
        sudo -u $SUDO_USER $EXEC_PATH/indexer --all --rotate --config $CONFIG_FILE
    else
        sudo -u $SUDO_USER $EXEC_PATH/indexer --all --config $CONFIG_FILE
    fi
    echo "done."
    echo
    RETVAL=$?
    return $RETVAL
}

case $* in
start)
    do_start
    ;;

stop)
    do_stop
    ;;

status)
    do_status
    ;;

reindex)
    do_reindex
    ;;

*)
    echo "usage: $0 {start|stop|status|reindex}" >&2

    exit 1
    ;;
esac

exit $RETVAL
